flags:
  semigroups:
    bytestring-builder: false
extra-package-dbs: []
packages:
- .
extra-deps:
- aeson-1.2.3.0
- base-compat-0.9.3
- fail-4.9.0.0
- integer-logarithms-1.0.2
- scientific-0.3.5.2
- semigroups-0.18.2
- tagged-0.8.4
- th-abstraction-0.2.6.0
- uuid-types-1.0.3
resolver: lts-4.2
